//[assembly: System.Reflection.AssemblyVersion("1.9.0.1")]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Reflection.AssemblyCompany("OLDD")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Reflection.AssemblyCopyright("Copyright ©  2018")]
[assembly: System.Reflection.AssemblyDescription("")]
//[assembly: System.Reflection.AssemblyFileVersion("1.9.0.1")]
[assembly: System.Reflection.AssemblyProduct("ScienceAlert")]
[assembly: System.Reflection.AssemblyTitle("ScienceAlert")]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.InteropServices.Guid("de7585d5-53eb-408c-ba04-a7bcee8f51a4")]


[assembly: KSPAssemblyDependency("ClickThroughBlocker", 1, 0)]
[assembly: KSPAssemblyDependency("ToolbarController", 1, 0)]